[package]
name = "basics"
version = "0.1.0"
authors = ["Matthew Scheffel <matt@dataheck.com>", "Foorack <max@foorack.com>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yew-bootstrap = { path = "../../packages/yew-bootstrap" }